DefaultContentLanguage: en
baseurl: https://reece.github.io
copyright: '2021, Reece Hart <reecehart@gmail.com>'
disqusShortname: ''
paginate: 10
taxonomies:
  category: categories
  series: series
  tag: tags
theme: hugo-clarity

