enableInlineShortcodes: true
footnoteReturnLinkContents: ^
privacy:
  instagram:
    disabled: false
    simple: true
  twitter:
    disableInlineCSS: true
    disabled: false
    enableDNT: true
    simple: true
  vimeo:
    disabled: false
    simple: true
  youtube:
    disabled: false
    privacyEnhanced: true
timeout: 30000

