main:
- name: Home
  url: ''
  weight: -110
- name: Archives
  url: post/rich-content/
  weight: -109

# - identifier: Links
#   name: Links
#   weight: -108
# - name: LinkedIn
#   parent: Links
#   url: https://www.linkedin.com/
# - name: Twitter
#   parent: Links
#   url: https://twitter.com/

- name: About
  url: about/
  weight: -107

social:
- name: github
  type: social
  url: https://github.com/reece
  weight: 1
- name: twitter
  url: https://twitter.com/reecehart
  weight: 2
- name: linkedin
  url: https://www.linkedin.com/in/reece
  weight: 3
- name: rss
  url: index.xml
  weight: 4

