author:
  name: Jane Doe
centerLogo: false
codeLineNumbers: false
codeMaxLines: 7
enableMathNotation: false
enforceLightMode: false
fallBackOgImage: images/thumbnail.png
figurePositionLabel: Figure
figurePositionShow: false
ga_analytics: XXXXXXXXXX
iconsDir: icons/
introDescription: Technologist, perpetual student, teacher, continual incremental
  improvement.
languageMenuName: "\U0001F310"
largeTwitterCard: false
logo: logos/logo.png
mainSections:
- post
matomo_analytics:
  enable: false
  matomoDomain: matomo.example.com
  matomoSiteID: '1'
  websiteDomain: example.com
mobileNavigation: left
numberOfTagsShown: 14
plausible_analytics:
  enable: false
  websiteDomain: example.com
twitter: '@janedoe'

