author:
  name: Reece Hart
centerLogo: false
codeLineNumbers: true
codeMaxLines: 7
enableMathNotation: false
enforceLightMode: false
fallBackOgImage: images/thumbnail.png
figurePositionLabel: Figure
figurePositionShow: false
ga_analytics: XXXXXXXXXX
iconsDir: icons/
introDescription: 'husband / dad / community agent / scientist + engineer'
languageMenuName: "\U0001F310"
largeTwitterCard: false
# logo: R.gif
mainSections:
- post
mobileNavigation: left
numberOfTagsShown: 14
twitter: '@reecehart'
