# See https://squidfunk.github.io/mkdocs-material/
# https://www.mkdocs.org/user-guide/deploying-your-docs/#organization-and-user-pages
# https://github.com/mkdocs/mkdocs/wiki/MkDocs-Plugins

site_name: Reece Hart
use_directory_urls: true
#strict: true

plugins:
  - autolinks
  - awesome-pages
  - blogging:
      dirs: [.]
      size: 5
      paging: false
      features:
        tags:
          index_page: tags.md

  #- mermaid2
  - glightbox
  - search

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      toc_depth: 1
      permalink: "#"

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/reece
#    - icon: fontawesome/brands/twitter
#      link: https://twitter.com/biocommons_ann

extra_css:
  - stylesheets/extra.css

theme:
  name: material

  features:
    - navigation.indexes
    - navigation.instant
    #- navigation.tabs.sticky
    - navigation.expand
    - navigation.tracking
    - navigation.sections
    - search.highlight
    - toc.follow
    # - toc.integrate

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: amber
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Ubuntu
    code: Roboto Mono
  logo: static/R.ico
  favicon: static/R.ico
